name: Send Reminders

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalışır

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reminder API
        run: |
          curl -X GET ${{ secrets.VERCEL_URL }}/api/cron/send-reminders \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" 